export const person = {
  fullName: "Moh. Fajar Sodiq",
  displayName: "FAJAR SODIQ",
  headline: "Infrastructure | DevOps | Networking | IoT | Software",
  role: "IT MANAGER",
  company: "PT. Citius Solusi Indonesia",
  location: "Jakarta, Indonesia",
  email: "fajar.shodiq@citius.co.id",
  phone: "+62 896-8642-2239",
  website: "https://fajarsodiq.com",
  intro:
    "Telecommunication Engineering graduate with over 5 years of experience in IT infrastructure, networking, and project leadership.",
};

export const codeSnippets = [
  // --- Linux ---
  "$ ping -c 4 10.0.0.1",
  "$ ssh admin@core-switch-01",
  "$ systemctl status firewalld",
  "$ traceroute gateway.local",
  "$ ip route show default",
  "$ ip addr show eth0",
  "$ netstat -tulpn",
  "$ ss -tulwn",
  "$ dig google.com",
  "$ nslookup 8.8.8.8",
  "$ curl -I https://gateway.local",
  "$ tcpdump -i eth0 port 80",
  "$ nmap -sV 192.168.1.0/24",
  "$ iptables -L -n",
  "$ tail -f /var/log/syslog",
  "$ df -h",
  "$ scp file.txt user@10.0.0.5:/tmp",

  // --- Networking status / output ---
  "> [VPN] tunnel established",
  "> uptime: 342 days",
  "> [OK] backup completed",
  "> Link state: UP",
  "> DHCP lease acquired: 192.168.1.42",
  "> NTP sync: success",
  "> SNMP trap received",
  "> Interface Gi0/1 changed state to up",

  // --- Cisco IOS ---
  "Router> enable",
  "Router# configure terminal",
  "Router(config)# hostname CoreRouter",
  "Router(config)# interface gi0/0",
  "Router(config-if)# ip address 192.168.1.1 255.255.255.0",
  "Router(config-if)# no shutdown",
  "Switch# show vlan brief",
  "Switch(config)# vlan 10",
  "Switch(config-vlan)# name Sales",
  "Switch(config)# interface fa0/1",
  "Switch(config-if)# switchport mode access",
  "Switch(config-if)# switchport access vlan 10",
  "Router# show ip route",
  "Router# show running-config",
  "Router# copy running-config startup-config",
  "Router(config)# router ospf 1",
  "Router(config-router)# network 10.0.0.0 0.0.0.255 area 0",
  "Router# show ip interface brief",
  "Router# show cdp neighbors",
  "Switch# show interfaces trunk",
  "Router(config)# access-list 10 permit 192.168.1.0 0.0.0.255",
  "Router# ping 8.8.8.8",
  "Router# show version",
  "Router(config-if)# description WAN-Link-to-ISP",
  "Switch# show spanning-tree",
] as const;

export const heroSkills = [
  "FULL STACK",
  "SYSTEM DESIGN",
  "API DEVELOPMENT",
  "REST API",
  "MICROSERVICES",
  "JAVASCRIPT",
  "PYTHON",
  "PHP",
  "JAVA",
  "C++",
  "C#",
  "SQL",
  "REACT",
  "NEXT.JS",
  "VUE.JS",
  "HTML",
  "CSS",
  "TAILWIND CSS",
  "SHADCN/UI",
  "NODE.JS",
  "LARAVEL",
  "MYSQL",
  "POSTGRESQL",
  "INFRASTRUCTURE",
  "SERVER",
  "LINUX",
  "NETWORKING",
  "LAN",
  "WAN",
  "TCP/IP",
  "DNS",
  "VPN",
  "FIREWALL",
  "SD-WAN",
  "DEVOPS",
  "DOCKER",
  "CI/CD",
  "GITHUB ACTIONS",
  "GITLAB CI",
  "NGINX",
  "TRAEFIK",
  "CLOUDFLARE",
  "VPS",
  "CLOUD",
  "SERVER DEPLOYMENT",
  "IoT",
  "IoT SYSTEMS",
  "MQTT",
  "WEBHOOK",
  "AUTOMATION",
  "N8N",
  "GIT",
  "GITHUB",
  "PROJECT MANAGEMENT",
  "TECHNICAL LEADERSHIP",
  "TECHNICAL SUPPORT",
] as const;

export const sections = [
  { id: "hero", num: "01", label: "HOME" },
  { id: "about", num: "02", label: "ABOUT" },
  { id: "experience", num: "03", label: "EXPERIENCE" },
  { id: "skills", num: "04", label: "SKILLS" },
  { id: "work", num: "05", label: "WORK" },
  { id: "contact", num: "06", label: "CONTACT" },
] as const;

export const about = {
  heading: ["BUILDING", "RELIABLE", "SYSTEMS."],
  paragraphs: [
    "Telecommunication Engineering graduate with over 5 years of experience in IT infrastructure, networking, and project leadership. Skilled in LAN/WAN troubleshooting, VPN setup, firewall management, and IT system implementation. Strong background in vendor coordination, documentation, and project delivery.",
    "Currently preparing for Cisco CCNA and Mikrotik MTCNA certifications.",
  ],
  stat: { value: "5+", label: "YEARS OF EXPERIENCE" },
};

export const experience = [
  {
    period: "2026 — NOW",
    title: "IT MANAGER",
    company: "PT. Citius Solusi Indonesia",
    current: true,
    responsibilities: [
      "1. Develop and execute IT strategy aligned with business objectives.",
      "2. Manage IT operations, projects, and vendors to ensure service delivery and compliance.",
      "3. Oversee IT budgeting and resource optimization to maximize ROI.",
      "4. Ensure secure, scalable, and reliable IT systems supporting organizational growth.",
    ],
  },
  {
    period: "2025 — 2026",
    title: "IT PROJECT LEADER",
    company: "PT. Citius Solusi Indonesia",
    current: false,
    responsibilities: [
      "1. Led IT infrastructure and telecommunication projects, ensuring on-time and on-budget delivery.",
      "2. Coordinated cross-functional teams and vendors, improving project delivery efficiency.",
      "3. Oversaw system implementation, testing, and handover with 100% customer acceptance.",
      "4. Provided support for LAN/WAN troubleshooting, VPN setup, and firewall configurations.",
    ],
  },
  {
    period: "2022 — 2025",
    title: "DOCUMENT & QUALITY CONTROL",
    company: "PT. Citius Solusi Indonesia",
    current: false,
    responsibilities: [
      "1. Monitoring team activities and document submissions (Survey & ATP) to vendors.",
      "2. Direct Review Meetings (DRM) for site surveys.",
      "3. Performed quality inspections of telecommunication equipment installations based on customer standards.",
      "4. Created and updated Site Implementation Designs and As-Built Drawings.",
    ],
  },
  {
    period: "2021 — 2022",
    title: "DOCUMENT CONTROL",
    company: "PT. Dexa Energy",
    current: false,
    responsibilities: [
      "1. Coordinated document submission and survey reporting to vendors.",
      "2. Monitored asset tagging and ensured installation materials matched BoQ.",
      "3. Performed quality inspections of telecommunication equipment installations based on customer standards.",
    ],
  },
  {
    period: "2020 — 2021",
    title: "IT TECHNICIAN",
    company: "GoLaptop Store",
    current: false,
    responsibilities: [
      "1. Diagnosed and repaired computer and laptop hardware and software issues.",
      "2. Installed and maintained LAN networks, routers, and Wi-Fi systems.",
      "3. Configured basic firewalls, VPNs, and access control systems for small businesses.",
      "4. Managed inventory and procurement of computer repair parts.",
    ],
  },
] as const;

export const capabilities = [
  { num: "01", title: "IT INFRASTRUCTURE", desc: "On-Prem & Hybrid Environment" },
  { num: "02", title: "NETWORKING", desc: "LAN · WAN · Fiber Optic · Wireless" },
  { num: "03", title: "CCTV & SURVEILLANCE", desc: "Design · Configuration · Troubleshooting" },
  { num: "04", title: "CLOUD & SERVER", desc: "Provisioning · Configuration · Optimization" },
  { num: "05", title: "NETWORK SECURITY", desc: "Firewall · VPN · Access Control · Risk Mitigation" },
  { num: "06", title: "IoT SYSTEMS", desc: "Device Connectivity · Network Integration · Monitoring" },
  { num: "07", title: "SOFTWARE & SYSTEM ADMINISTRATION", desc: "Basic SQL · Backup & Recovery · System Integration" },
  { num: "08", title: "PROJECT & VENDOR MANAGEMENT", desc: "Planning · Coordination · Delivery Oversight" },
  { num: "09", title: "IT BUDGETING", desc: "Resource Optimization" },
  { num: "10", title: "TECHNICAL DOCUMENTATION", desc: "Executive Reporting" },
] as const;

export const techStackNames = [
  "JAVASCRIPT",
  "PYTHON",
  "PHP",
  "JAVA",
  "REACT",
  "NEXT.JS",
  "VUE.JS",
  "NODE.JS",
  "LARAVEL",
  "HTML",
  "CSS",
  "TAILWIND CSS",
  "MYSQL",
  "POSTGRESQL",
  "DOCKER",
  "LINUX",
  "GIT",
  "GITHUB",
  "NGINX",
] as const;

export const selectedWork = [
  {
    num: "01",
    category: "IT INFRASTRUCTURE",
    desc: "On-premise and hybrid environment planning, provisioning, and lifecycle management.",
    tags: ["ON-PREM", "HYBRID", "SYSTEM IMPLEMENTATION"],
  },
  {
    num: "02",
    category: "NETWORK & SECURITY",
    desc: "LAN/WAN troubleshooting, VPN setup, and firewall management across business environments.",
    tags: ["FIREWALL", "VPN", "ACCESS CONTROL"],
  },
  {
    num: "03",
    category: "IoT & MONITORING",
    desc: "Device connectivity, network integration, and monitoring for connected systems.",
    tags: ["IoT", "MONITORING", "INTEGRATION"],
  },
  {
    num: "04",
    category: "CCTV & SURVEILLANCE",
    desc: "Design, configuration, and troubleshooting of surveillance systems.",
    tags: ["CCTV", "DESIGN", "TROUBLESHOOTING"],
  },
  {
    num: "05",
    category: "SYSTEM INTEGRATION",
    desc: "Vendor coordination, documentation, and project delivery from survey to handover.",
    tags: ["VENDOR MGMT", "DOCUMENTATION", "DELIVERY"],
  },
  {
    num: "06",
    category: "SOFTWARE ENGINEERING",
    desc: "Built an ERP system from the ground up, and develops custom software tailored to specific business requirements.",
    tags: ["ERP", "CUSTOM SOFTWARE", "FULL STACK"],
  },
] as const;

export const education = {
  school: "POLITEKNIK NEGERI MALANG",
  program: "D3 Telecommunication Engineering",
  gpa: "3.54 / 4.00",
  period: "2017 — 2020",
};

export const personalBrand = {
  lines: ["I TURN", "COMPLEX", "SYSTEMS", "INTO", "RELIABLE", "SOLUTIONS."],
};

export const contact = {
  heading: ["LET'S BUILD", "SOMETHING", "RELIABLE."],
  supporting: "Have a project, technical challenge, or opportunity?",
};
